# Sử dụng image php:8.2-apache làm base image
FROM php:8.2-apache

# Cấu hình làm việc (tuỳ chọn)
WORKDIR /var/www/html

# Ghi chú: Yêu cầu mount mã nguồn từ host vào container
# nên ta không dùng lệnh COPY ở đây. Chạy với cờ -v
